server:
  port: 8080

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://localhost:3306/payments
    username: root
    password: Root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true              
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

logging:
  level:
    com.amurfu.payments: DEBUG
    org.hibernate.SQL: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
# -----------------------------------------------------------------------------

# ─── Perfil “docker” — se activa con SPRING_PROFILES_ACTIVE=docker ────────────
---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:mysql://${DB_HOST:mysql}:3306/${DB_NAME:payments}
    username: ${DB_USER:root}
    password: ${DB_PASS:Root}

  rabbitmq:
    host: ${RABBIT_HOST:rabbitmq}
    port: 5672
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}

logging:
  level:
    com.amurfu.payments: INFO     # menos verboso en contenedor
    org.hibernate.SQL: OFF
